*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 18.03.2021 at 03:46:26
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZESTM_HEADER....................................*
FORM GET_DATA_ZESTM_HEADER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZESTM_HEADER_OBJ WHERE
(VIM_WHERETAB) .
    CLEAR ZESTM_HEADER .
ZESTM_HEADER-MANDT =
ZESTM_HEADER_OBJ-MANDT .
ZESTM_HEADER-HEADER_ID =
ZESTM_HEADER_OBJ-HEADER_ID .
ZESTM_HEADER-HEADER_NAME =
ZESTM_HEADER_OBJ-HEADER_NAME .
<VIM_TOTAL_STRUC> = ZESTM_HEADER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZESTM_HEADER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZESTM_HEADER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZESTM_HEADER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZESTM_HEADER_OBJ WHERE
  HEADER_ID = ZESTM_HEADER-HEADER_ID .
    IF SY-SUBRC = 0.
    DELETE ZESTM_HEADER_OBJ .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZESTM_HEADER_OBJ WHERE
  HEADER_ID = ZESTM_HEADER-HEADER_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZESTM_HEADER_OBJ.
    ENDIF.
ZESTM_HEADER_OBJ-MANDT =
ZESTM_HEADER-MANDT .
ZESTM_HEADER_OBJ-HEADER_ID =
ZESTM_HEADER-HEADER_ID .
ZESTM_HEADER_OBJ-HEADER_NAME =
ZESTM_HEADER-HEADER_NAME .
    IF SY-SUBRC = 0.
    UPDATE ZESTM_HEADER_OBJ ##WARN_OK.
    ELSE.
    INSERT ZESTM_HEADER_OBJ .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZESTM_HEADER-UPD_FLAG,
STATUS_ZESTM_HEADER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZESTM_HEADER.
  SELECT SINGLE * FROM ZESTM_HEADER_OBJ WHERE
HEADER_ID = ZESTM_HEADER-HEADER_ID .
ZESTM_HEADER-MANDT =
ZESTM_HEADER_OBJ-MANDT .
ZESTM_HEADER-HEADER_ID =
ZESTM_HEADER_OBJ-HEADER_ID .
ZESTM_HEADER-HEADER_NAME =
ZESTM_HEADER_OBJ-HEADER_NAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZESTM_HEADER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZESTM_HEADER-HEADER_ID TO
ZESTM_HEADER_OBJ-HEADER_ID .
MOVE ZESTM_HEADER-MANDT TO
ZESTM_HEADER_OBJ-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZESTM_HEADER_OBJ'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZESTM_HEADER_OBJ TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZESTM_HEADER_OBJ'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZESTM_ITEM......................................*
FORM GET_DATA_ZESTM_ITEM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZESTM_ITEM_OBJ WHERE
(VIM_WHERETAB) .
    CLEAR ZESTM_ITEM .
ZESTM_ITEM-MANDT =
ZESTM_ITEM_OBJ-MANDT .
ZESTM_ITEM-HEADER_ID =
ZESTM_ITEM_OBJ-HEADER_ID .
ZESTM_ITEM-ITEM_ID =
ZESTM_ITEM_OBJ-ITEM_ID .
ZESTM_ITEM-ITEM_NAME =
ZESTM_ITEM_OBJ-ITEM_NAME .
<VIM_TOTAL_STRUC> = ZESTM_ITEM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZESTM_ITEM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZESTM_ITEM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZESTM_ITEM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZESTM_ITEM_OBJ WHERE
  HEADER_ID = ZESTM_ITEM-HEADER_ID AND
  ITEM_ID = ZESTM_ITEM-ITEM_ID .
    IF SY-SUBRC = 0.
    DELETE ZESTM_ITEM_OBJ .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZESTM_ITEM_OBJ WHERE
  HEADER_ID = ZESTM_ITEM-HEADER_ID AND
  ITEM_ID = ZESTM_ITEM-ITEM_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZESTM_ITEM_OBJ.
    ENDIF.
ZESTM_ITEM_OBJ-MANDT =
ZESTM_ITEM-MANDT .
ZESTM_ITEM_OBJ-HEADER_ID =
ZESTM_ITEM-HEADER_ID .
ZESTM_ITEM_OBJ-ITEM_ID =
ZESTM_ITEM-ITEM_ID .
ZESTM_ITEM_OBJ-ITEM_NAME =
ZESTM_ITEM-ITEM_NAME .
    IF SY-SUBRC = 0.
    UPDATE ZESTM_ITEM_OBJ ##WARN_OK.
    ELSE.
    INSERT ZESTM_ITEM_OBJ .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZESTM_ITEM-UPD_FLAG,
STATUS_ZESTM_ITEM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZESTM_ITEM.
  SELECT SINGLE * FROM ZESTM_ITEM_OBJ WHERE
HEADER_ID = ZESTM_ITEM-HEADER_ID AND
ITEM_ID = ZESTM_ITEM-ITEM_ID .
ZESTM_ITEM-MANDT =
ZESTM_ITEM_OBJ-MANDT .
ZESTM_ITEM-HEADER_ID =
ZESTM_ITEM_OBJ-HEADER_ID .
ZESTM_ITEM-ITEM_ID =
ZESTM_ITEM_OBJ-ITEM_ID .
ZESTM_ITEM-ITEM_NAME =
ZESTM_ITEM_OBJ-ITEM_NAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZESTM_ITEM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZESTM_ITEM-HEADER_ID TO
ZESTM_ITEM_OBJ-HEADER_ID .
MOVE ZESTM_ITEM-ITEM_ID TO
ZESTM_ITEM_OBJ-ITEM_ID .
MOVE ZESTM_ITEM-MANDT TO
ZESTM_ITEM_OBJ-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZESTM_ITEM_OBJ'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZESTM_ITEM_OBJ TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZESTM_ITEM_OBJ'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
